services:
  - type: web
    name: vera-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn bot:app --host 0.0.0.0 --port $PORT --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TOGETHER_API_KEY
        sync: false
      - key: CEREBRAS_API_KEY
        sync: false
      - key: SAMBANOVA_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TEAM_NAME
        value: Vera-Dheera-Soora
      - key: CONTACT_EMAIL
        value: your-email@example.com
    healthCheckPath: /v1/healthz
